apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-orchestrator
  ports:
      - protocol: TCP
        port: 8501
        targetPort: 8501
  type: {{ .Values.service.type }}
